# Generated by Django 4.0.4 on 2022-06-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppy_website2', '0003_alter_product_brand_alter_product_category_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='Processor',
            new_name='processor',
        ),
    ]
