# Generated by Django 4.0.2 on 2022-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppy_website2', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='processor',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rom',
            field=models.CharField(max_length=20),
        ),
    ]
