# Generated by Django 4.0.2 on 2022-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppy_website2', '0006_remove_mobile_processor_alter_mobile_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='processor',
            field=models.TextField(default=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rom',
            field=models.IntegerField(default=128),
        ),
    ]
