# Generated by Django 4.0.2 on 2022-06-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppy_website2', '0007_mobile_processor_alter_mobile_ram_alter_mobile_rom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='processor',
            field=models.TextField(max_length=100),
        ),
    ]
