# Generated by Django 4.0.2 on 2022-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppy_website2', '0008_alter_mobile_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='processor',
            field=models.CharField(max_length=100),
        ),
    ]
